version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: mahmud24/notes-backend:latest
    container_name: nestjs_app
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - db
    restart: unless-stopped

  migrations:
    image: mahmud24/notes-backend:latest
    command: sh -c "npx drizzle-kit push --config=src/db/drizzle.config.ts"
    env_file:
      - .env.docker
    depends_on:
      - db
    restart: "no"

volumes:
  pg_data:



# docker compose -f docker-compose.prod.yml up
# docker compose -f docker-compose.prod.yml down

# ( -f ) means file name, if we don't use it then default is docker-compose.yml